LearningApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('blog.urls')),
    path('account/',include('account.urls'))
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import api,article_detais,category_list,ArticleList,ArticleDetails,CategoryList,AuthorList
app_name="blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),

    path('api', api, name="api"),

    path('article/<slug:slug>', ArticleDetails.as_view(), name="article_detais_url"),

    path('category/<slug:slug>', CategoryList.as_view(), name="category_list_url"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category_list_url"),

    path('author/<slug:username>', AuthorList.as_view(), name="author_list_url"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author_list_url"),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.html import format_html
from Extentions.utils import jalali_converter
from django.template.defaultfilters import truncatewords  # or truncatewords

#my Managers
class ArticleManager(models.Manager):
    def published_article(self):
        return self.filter(status='p')
class CategoryManager(models.Manager):
    def active_category(self):
        return self.filter(status=True)

class Category(models.Model):
    parent=models.ForeignKey('self',default=None, null=True, blank=True, verbose_name="زیردسته",related_name='children',on_delete=models.SET_NULL)
    title = models.CharField(max_length=120, null=False, blank=False, verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=120, unique=True, null=False, blank=False, verbose_name="آدرس دسته بندی")
    status=models.BooleanField(default=True,verbose_name="آیا نمایش داده شود؟")
    position=models.IntegerField(verbose_name="پوزیشن")
    class Meta():
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering =['parent__id','position']
    def __str__(self):
        return self.title
    objects = CategoryManager()

class article(models.Model):
    STATUS_CHOICES={
        ('d','Draft'),
        ('p','Publish'),
    }
    author=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,verbose_name="نویسنده",related_name="article_author_rel")
    title=models.CharField(max_length=120,null=False, blank= False,verbose_name="عنوان مقاله")
    slug=models.SlugField(max_length=120,unique=True,null=False, blank= False,verbose_name="آدرس مقاله")
    category=models.ManyToManyField(Category,verbose_name="دسته بندی",related_name='articles_rela')
    description=models.TextField(verbose_name="متن مقاله")
    thumbnail=models.ImageField(upload_to="images",verbose_name="تصویر مقاله")
    publish_time=models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    created=models.DateTimeField(auto_now_add=True,verbose_name="")
    updated=models.DateTimeField(auto_now=True,verbose_name="")
    status=models.CharField(max_length=1,choices=STATUS_CHOICES,verbose_name="وضعیت انتشار")
    class Meta():
        verbose_name="مقاله"
        verbose_name_plural="مقالات"
        ordering =['-publish_time']

    def __str__(self):
        return self.title
    def thumbnail_tag(self):
        return format_html("<img width='100' height='85' style='border-radius : 5px' src='{}'>".format(self.thumbnail.url))
    def jpublish_time(self):
        return jalali_converter(self.publish_time)
   # def category_published(self):
   #     return self.category.filter(status=True)
    def short_description(self):
        return truncatewords(self.description,10)
    def article_category(self):
        cate=[]
        for category in self.category.all():
            cate.append(category.title)
        return ",".join(cate)
    jpublish_time.short_description="زمان انتشار"
    thumbnail_tag.short_description='عکس بند انگشتی'
    objects=ArticleManager()

blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render,get_object_or_404
from    django.http import HttpResponse,JsonResponse
from .models import article,Category
from django.contrib.auth.models import User
from django.views.generic import ListView,TemplateView,DetailView
            #def home(request):
            #    return HttpResponse("Hello world!")

#def home(request):
#    context={
#        "username":"reza",
#        "age":32,
#        "job":"developer",
#    }
#    return render(request, "home.html",context)
#def home(request,page=1):
#    articles_list=article.objects.published_article()
#    paginator=Paginator(articles_list,3)
#    #page=request.GET.get('page')
#    articles=paginator.get_page(page)
#    context={
#        "article": articles, #"article":article.objects.all().filter(status="p"),# - nozoli
#    }
#    return render(request, "index.html",context)
class ArticleList(ListView):
    #model = article
    template_name = "article_list.html"#dar sorat adam estefade bayad name index.html ra be article_list.html taghir dahim
    context_object_name = "article"#dar sorat adam estefade dar template bayad benevisim===>object_list
    queryset = article.objects.published_article()
    paginate_by = 6
def article_detais(request,slug):
    context={
        'article': get_object_or_404(article.objects.published_article(), slug=slug), # 'article':get_object_or_404(article,slug=slug,status="p"),

    }
    return render(request,'blog/post.html',context)
class ArticleDetails(DetailView):
    template_name = "blog/post.html"
    context_object_name="article"
    def get_object(self, queryset=None):
        slug=self.kwargs.get('slug')
        return get_object_or_404(article.objects.published_article(), slug=slug)

def category_list(request,slug,page=1):
    category=get_object_or_404(Category,slug=slug,status=True)
    articles_list = category.articles_rela.published_article()
    paginator = Paginator(articles_list, 3)
    articles = paginator.get_page(page)

    context={
        "category":category,
        "articles":articles,
    }
    return  render(request,'blog/category.html',context)
class CategoryList(ListView):
    template_name = "blog/category_list.html"
    paginate_by = 3
    def get_queryset(self):
        global category
        slug=self.kwargs.get("slug")
        category=get_object_or_404(Category.objects.active_category(), slug=slug, )
        return category.articles_rela.published_article()
    def get_context_data(self, *, object_list=None, **kwargs):
        context=super().get_context_data(**kwargs)
        context["category"]=category
        return context

class AuthorList(ListView):
    template_name = "blog/author_list.html"
    paginate_by = 3
    def get_queryset(self):
        global author_category
        username=self.kwargs.get("username")
        author_category=get_object_or_404(User, username=username, )
        return author_category.article_author_rel.published_article()
    def get_context_data(self, *, object_list=None, **kwargs):
        context=super().get_context_data(**kwargs)
        context["author_category"]=author_category
        return context
def api(request):
    data={
        "1":{
            "title":"مقاله ی چگونگی کسب و کار در جهان موازی",
            "id":20,
            "category":"حسابداری",
        },
        "2":{
            "title":"تکنولوژی های قدیمی",
            "id":28,
            "category":"کامپیوتر",
        },
        "3":{
            "title":"فوتبال پشمکی",
            "id":23,
            "category":"ورزشی",
        },
    }
    return JsonResponse(data)

blog/templates/article_list.html
{% extends 'list.html' %}
{% load static %}
{% block header %}{% endblock %}


{% block previous_page_url %}
    {% url 'blog:home'  page_obj.previous_page_number%}

{% endblock %}

{% block next_page_url %}

    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

blog/templates/author_list.html
{% extends 'list.html' %}
{% load static %}
{% block header %}
      <h3 class="alert alert-primary text-center">نویسنده : {{ author_category.get_full_name }}</h3>

{% endblock %}


{% block previous_page_url %}
    {% url 'blog:author_list_url'  author_category.username  page_obj.previous_page_number%}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:author_list_url'  author_category.username page_obj.next_page_number %}
{% endblock %}

blog/templates/category_list.html
{% extends 'list.html' %}
{% load static %}
{% block header %}
      <h3 class="alert alert-primary text-center">دسته بندی : {{ category.title }}</h3>

{% endblock %}


{% block previous_page_url %}
    {% url 'blog:category_list_url'  category.slug  page_obj.previous_page_number%}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category_list_url'  category.slug page_obj.next_page_number %}
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
  <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبی لاگ</h1>
            <span class="subheading"> لاگی از سراسر وب </span>
          </div>
        </div>
      </div>
    </div>
  </header>
<!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          {% for arttc in article %}
              <div class="post-preview">
                  <a href="{% url "blog:article_detais_url" arttc.slug %}">
                      <h2 class="post-title">
                          {{ arttc.title }}
                      </h2>
                      <h3 class="post-subtitle">
                          {{ arttc.description|truncatewords:30}}
                      </h3>
                  </a>
                  <p class="post-meta">نویسنده
                      <a href="#">طهماسبی</a>
                      {{ arttc.jpublish_time }}</p>
                  <div>
                      {% for cat in arttc.category_published.all %}
                        <a href="{% url "blog:category_list_url" cat.slug %}">#{{ cat.title }}</a>
                      {% endfor %}
                  </div>
              </div>
              <hr>
          {% endfor %}

        <!-- Pager -->
       {% if is_paginated %}
           <div class="clearfix pager-botton" >
            {% if page_obj.has_previous  %} {% comment %} {% if article.has_previous  %}#chon az class base view estefade kardim in ravesh sahih nemibashad {% endcomment %}
                <a class="btn btn-primary float-right  ml-3" href="{% url 'blog:home'  page_obj.previous_page_number%}"> پست های جدید&rarr;</a>
            {% endif %}

            {% if page_obj.has_next %}
                <a class="btn btn-primary float-right" href="{% url 'blog:home' page_obj.next_page_number %}"> پست های قدیم&larr;</a>{% comment %}<a class="btn btn-primary float-right" href="{% url 'blog:home' %}?page={{ article.next_page_number  }}"> پست های قدیم&larr;</a>{% endcomment %}
            {% endif %}
           </div>
      {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
  <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبی لاگ</h1>
            <span class="subheading"> لاگی از سراسر وب </span>
          </div>
        </div>
      </div>
    </div>
  </header>
<!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      {% block header %}{% endblock %}
          {% for arttc in object_list %}
              <div class="post-preview">
                  <a href="{% url "blog:article_detais_url" arttc.slug %}">
                      <h2 class="post-title">
                          {{ arttc.title }}
                      </h2>
                      <h3 class="post-subtitle">
                          {{ arttc.description|truncatewords:30}}
                      </h3>
                  </a>
                  <p class="post-meta">نویسنده
                      <a href="{% url "blog:author_list_url" arttc.author %}">{{arttc.author.get_full_name }}</a>
                      {{ arttc.jpublish_time }}</p>
                  <div>
                      {% for cat in arttc.category.active_category %}
                        <a href="{% url "blog:category_list_url" cat.slug %}">#{{ cat.title }}</a>
                      {% endfor %}
                  </div>
              </div>
              <hr>
          {% endfor %}
   <!-- Pager -->
       {% if is_paginated %}
           <div class="clearfix pager-botton" >
            {% if page_obj.has_previous  %} {% comment %} {% if article.has_previous  %}#chon az class base view estefade kardim in ravesh sahih nemibashad {% endcomment %}
                <a class="btn btn-primary float-right  ml-3" href="{% block previous_page_url %}{% endblock %}"> پست های جدید&rarr;</a>
            {% endif %}

            {% if page_obj.has_next %}
                <a class="btn btn-primary float-right" href="{% block next_page_url %}{% endblock %}"> پست های قدیم&larr;</a>{% comment %}<a class="btn btn-primary float-right" href="{% url 'blog:home' %}?page={{ article.next_page_number  }}"> پست های قدیم&larr;</a>{% endcomment %}
            {% endif %}
           </div>
      {% endif %}

      </div>
    </div>
  </div>
{% endblock %}

blog/templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} | {{ article.title }}{% endblock %}
{% block main %}
  <header class="masthead" style="background-image: url('{{ article.thumbnail.url }}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{ article.title }}</h1>
              <time>{{ article.jpublish_time }}</time>
               <div>
                      {% for cat in article.category_published.all %}
                         <a class="btn-link" href="{% url "blog:category_list_url" cat.slug %}">#{{ cat.title }}</a> {% comment %}<span >#{{ cat.title }}</span>{% endcomment %}
                      {% endfor %}
                  </div>
          </div>
        </div>
      </div>
    </div>
  </header>
<!-- Post Content -->
  <article>
    <div class="container ">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-justify">
         {{ article.description|linebreaks }}
        </div>
      </div>
    </div>
  </article>
{% endblock %}